name: Build Windows EXE

on:
  push:
    branches: [ "main" ]   # run on push to main
  workflow_dispatch:        # allow manual run

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build exe
      run: |
        pyinstaller --onefile ^
          --collect-all cv2 ^
          --collect-all numpy ^
          --collect-all numba ^
          RemoveBG.py

    - name: Upload exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/RemoveBG.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: "Windows Build v1.0.0"
        files: dist/RemoveBG.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}